/*
 * Copyright (c) 2021, Alibaba Group Holding Limited;
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class GXConstants {
  /**
   * template类型
   */
  static readonly GXNodeTypeTemplate: string = 'gaia-template';
  /**
   * custom类型
   */
  static readonly GXNodeTypeCustom: string = 'custom';
  /**
   * scroll类型
   */
  static readonly GXNodeTypeScroll: string = 'scroll';
  /*
   * slider类型
   */
  static readonly GXNodeTypeSlider: string = 'slider';
  /*
   * grid类型
   */
  static readonly GXNodeTypeGrid: string = 'grid';
}
