@startuml

actor Business

group 绑定数据流程

    Business -> GXEngine: bindData

    group 更新上下文

        GXEngine -> GXTemplateContext: getContext

        GXEngine -> GXTemplateContext: updateContext

    end


    GXEngine --> GXRenderImpl: bindViewData

    group 更新节点树

        GXRenderImpl -> GXViewNodeTreeUpdater: build

        GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: updateNodeTree

        GXViewNodeTreeUpdater -> GXTemplateNode: reset

        GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: updateNestNode

        group 更新普通模板嵌套节点
            GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: updateNestNormalNode

            GXViewNodeTreeUpdater -> GXTemplateNode: initFinal

            group 更新节点
                GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: updateNode

                group 更新节点的Stretch样式

                    GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: nodeNodeStyle

                    alt 容器节点

                        GXViewNodeTreeUpdater -> GXStretchNode: updateContainerStyle

                        group 预计算容器高度
                            GXStretchNode -> GXNodeUtils: computeContainerHeightByItemTemplate

                            GXStretchNode -> GXNodeUtils: computeItemViewPort

                            GXStretchNode -> GXNodeUtils: computeItemSize

                            GXStretchNode -> GXNodeUtils: computeItemSizeByCreateAndBindNode

                            GXNodeUtils -> GXTemplateContext: createContext

                            GXNodeUtils <-- GXTemplateContext: return GXTemplateContext

                            GXNodeUtils -> GXEngine: createNode
                            GXNodeUtils <-- GXEngine: return GXNode

                            GXNodeUtils -> GXEngine: bindNodeData

                            GXStretchNode -> GXNodeUtils: computeContainerSize

                            GXStretchNode <-- GXNodeUtils: return Size
                        end

                        GXStretchNode -> GXStretchNode: updateStyleByFlexBox
                        GXStretchNode -> GXStretchNode: updateStyleByCssStyle

                    else 普通节点

                        GXViewNodeTreeUpdater -> GXStretchNode: updateNormalStyle
                        GXStretchNode -> GXStretchNode: updateStyleByFlexBox
                        GXStretchNode -> GXStretchNode: updateStyleByCssStyle

                    end

                end

                group 更新节点的样式
                    GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: nodeViewCss
                    GXViewNodeTreeUpdater -> GXViewText: setTextStyle
                    GXViewNodeTreeUpdater -> GXViewImage: setImageStyle
                    GXViewNodeTreeUpdater -> GXScrollAndGrid: bindContainerViewCss
                    GXViewNodeTreeUpdater -> GXView: bindViewCss
                end

                group 更新节点的数据
                    GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: nodeViewData

                    GXViewNodeTreeUpdater -> GXViewCustom: bindCustom
                    GXViewNodeTreeUpdater -> GXViewText: bindText
                    GXViewNodeTreeUpdater -> GXViewText: bindRichText
                    GXViewNodeTreeUpdater -> GXViewImage: bindImage
                    GXViewNodeTreeUpdater -> GXViewIconFont: bindIconFont
                    GXViewNodeTreeUpdater -> GXScrollAndGrid: bindScrollAndGrid
                    GXViewNodeTreeUpdater -> GXView: bindView

                end

                GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: nodeViewTrack

                GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: nodeViewEvent

                GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: nodeViewAnimation
            end
        end

        group  更新容器模板嵌套节点
            GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: updateNestContainerNode

            GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: getNestContainerTemplateData

            GXViewNodeTreeUpdater <-- GXViewNodeTreeUpdater: return JSONObject


            GXViewNodeTreeUpdater -> GXTemplateNode: initFinal

            group 更新节点
                GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: updateNode
            end
        end

        group 更新普通节点
            GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: updateNormalNode

            GXViewNodeTreeUpdater -> GXTemplateNode: initFinal

            group 更新节点
                GXViewNodeTreeUpdater -> GXViewNodeTreeUpdater: updateNode
            end
        end


        group 计算布局并更新
            GXViewNodeTreeUpdater -> GXNodeUtils: computeNodeTree
            GXViewNodeTreeUpdater -> GXViewLayoutParamsUtils: updateLayoutParams
        end

    end

end
@enduml
