@startuml

actor Business


group 创建视图流程

    Business -> GXEngine: createView

    group 创建上下文

        GXEngine -> GXTemplateContext: createContext

        GXEngine <-- GXTemplateContext: return GXTemplateContext

    end


    group 获取模板

        GXEngine -> GXDataImpl: getTemplateInfo

        GXEngine <-- GXDataImpl: return getTemplateInfo

    end

    group 创建视图

        GXEngine -> GXRenderImpl: createView

        group 创建Stretch节点树

            GXRenderImpl -> GXNodeTreeCreator: create

            group 创建节点树

                GXNodeTreeCreator -> GXNodeTreeCreator: createNode

                group 创建模板节点
                    GXNodeTreeCreator -> GXTemplateNode: createNode

                    GXTemplateNode -> GXTemplateInfo: findLayer
                    GXTemplateNode <-- GXTemplateInfo: return GXLayer

                    GXTemplateNode -> GXTemplateInfo: findCss
                    GXTemplateNode <-- GXTemplateInfo: return GXCss

                    GXTemplateNode -> GXTemplateInfo: findData
                    GXTemplateNode <-- GXTemplateInfo: return GXDataBinding

                    GXTemplateNode -> GXTemplateInfo: findEvent
                    GXTemplateNode <-- GXTemplateInfo: return GXDataBinding

                    GXTemplateNode -> GXTemplateInfo: findAnimation
                    GXTemplateNode <-- GXTemplateInfo: return GXAnimationBinding

                    GXNodeTreeCreator <-- GXTemplateNode: return GXTemplateNode
                end

                group 创建Stretch节点
                    GXNodeTreeCreator -> GXStretchNode: createNode

                    GXNodeTreeCreator -> GXStretchNode: createStretchStyle

                    GXNodeTreeCreator <-- GXStretchNode: return Style

                    GXNodeTreeCreator <-- GXStretchNode: return GXStretchNode
                end

                GXNodeTreeCreator -> GXNodeTreeCreator: initChildrenViewData

            end

            group 计算节点树

                GXNodeTreeCreator -> GXNodeTreeCreator: computeLayout

                GXNodeTreeCreator -> GXNodeTreeCreator: composeStretchNode

            end

            GXRenderImpl <-- GXNodeTreeCreator: return GXNode

        end

        group 创建视图树

            GXRenderImpl -> GXViewTreeCreator: build

            GXViewTreeCreator -> GXViewTreeCreator: withRootView

            GXViewTreeCreator -> GXViewFactory: createView

            GXViewTreeCreator <-- GXViewFactory: return View

            GXViewTreeCreator -> GXViewTreeCreator: createMergeViewChildTree

            GXViewTreeCreator -> GXViewTreeCreator: withChildView

            GXViewTreeCreator -> GXViewFactory: createView

            GXViewTreeCreator <-- GXViewFactory: return view

            GXRenderImpl <-- GXViewTreeCreator: return View

        end

        GXEngine <-- GXRenderImpl: return View

    end

    Business <-- GXEngine: return View

end


@enduml
