ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'
#
#ENV['POD_HEADER_FIX']='FALSE'
#ENV['POD_AUTOADD_SEARCH_NAME_LIST']=''
#disable_link_dynamic_framework!

target 'GaiaXiOSDemo' do
  platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # SDWebImage
  pod  'SDWebImage'
  
  # YYText
  pod  'YYText'
  
  # 曲线动画
  pod "GaiaMotionCurve", :path => '../../GaiaMotionCurve/src/iOS'
  
  # json
  pod  'JSONKit',         '2.1.2.2'

  # 网络
  pod 'SocketRocket',      '0.5.1'
  
end
