source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

#ENV['POD_HEADER_FIX']='FALSE'
#ENV['POD_AUTOADD_SEARCH_NAME_LIST']=''
#disable_link_dynamic_framework!

target 'GaiaXiOSDemo' do
  platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # 曲线动画
#  pod 'GaiaXiOS'
  pod  'GaiaXiOS',       :path=>'../GaiaXiOS'

  # 曲线动画
  pod 'GaiaMotionCurve'

  # SDWebImage
  pod  'SDWebImage'
  
  # YYText
  pod  'YYText'
  
  # 网络
  pod 'SocketRocket'
  
end
