#!/bin/bash

ROOT=`pwd`

ROOT_DATA=$ROOT/data
ROOT_TEMPLATES=$ROOT/templates

cd ..

GAIAX_ROOT=`pwd`

echo $ROOT
echo $ROOT_DATA
echo $ROOT_TEMPLATES

echo $GAIAX_ROOT

GAIAX_ANDROID_TEMPLATES=$GAIAX_ROOT/GaiaXAndroid/src/androidTest/assets/integration

echo $GAIAX_ANDROID_TEMPLATES

rm -rf $GAIAX_ANDROID_TEMPLATES
cp -r $ROOT_TEMPLATES $GAIAX_ANDROID_TEMPLATES

GAIAX_IOS_TEMPLATES=$GAIAX_ROOT/GaiaXiOS/GaiaXiOSTests/GaiaXiOSTests.bundle

echo $GAIAX_IOS_TEMPLATES

rm -rf $GAIAX_IOS_TEMPLATES
mkdir $GAIAX_IOS_TEMPLATES
cp -r $ROOT_TEMPLATES/* $GAIAX_IOS_TEMPLATES
