source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

target 'GaiaXSocket' do
  platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!
  
  pod 'SocketRocket',  '0.5.1'
    
end
