#!/bin/bash

ROOT=`pwd`

ROOT_DATA=$ROOT/data
ROOT_TEMPLATES=$ROOT/templates

cd ..

GAIAX_ROOT=`pwd`

echo $ROOT
echo $ROOT_DATA
echo $ROOT_TEMPLATES

echo $GAIAX_ROOT

GAIAX_ANDROID_DEMO_DATA=$GAIAX_ROOT/GaiaXAndroidDemo/app/src/main/assets/data
GAIAX_ANDROID_DEMO_TEMPLATES=$GAIAX_ROOT/GaiaXAndroidDemo/app/src/main/assets/templates

echo $GAIAX_ANDROID_DEMO_DATA
echo $GAIAX_ANDROID_DEMO_TEMPLATES

rm -rf $GAIAX_ANDROID_DEMO_DATA
rm -rf $GAIAX_ANDROID_DEMO_TEMPLATES
cp -r $ROOT_DATA $GAIAX_ANDROID_DEMO_DATA
cp -r $ROOT_TEMPLATES $GAIAX_ANDROID_DEMO_TEMPLATES


GAIAX_IOS_DEMO_DATA=$GAIAX_ROOT/GaiaXiOSDemo/GaiaXiOSDemo/Resource
GAIAX_IOS_DEMO_TEMPLATES=$GAIAX_ROOT/GaiaXiOSDemo/GaiaXiOSDemo/Resource/GaiaXTemplate.bundle

echo $GAIAX_IOS_DEMO_DATA
echo $GAIAX_IOS_DEMO_TEMPLATES

rm -rf $GAIAX_IOS_DEMO_TEMPLATES
mkdir $GAIAX_IOS_DEMO_TEMPLATES
cp -r $ROOT_TEMPLATES/* $GAIAX_IOS_DEMO_TEMPLATES

rm -rf $GAIAX_IOS_DEMO_DATA/*.json
cp -r $ROOT_DATA/* $GAIAX_IOS_DEMO_DATA