source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

target 'GaiaXiOS' do
  platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
    #Pods for GaiaXiOS
        
    # SDWebImage
    pod 'SDWebImage'

    # 曲线动画
    pod 'GaiaMotionCurve'

    pod 'GaiaXJS', :path =>'../GaiaXJSiOS'
    pod 'GaiaXSocket', :path => '../GaiaXSocketiOS'

end


target 'GaiaXiOSTests'  do
    
    # SDWebImage
    pod  'SDWebImage'

    # 曲线动画
    pod 'GaiaMotionCurve'

end
