source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

target 'GaiaXiOS' do
  platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
    #Pods for GaiaXiOS
        
    # YYText
    pod 'YYText'

    # SDWebImage
    pod 'SDWebImage'

    # 曲线动画
#    pod 'GaiaMotionCurve', :path => '../../GaiaMotionCurve/src/iOS'
    pod 'GaiaMotionCurve', '0.1.0'

end


target 'GaiaXiOSTests'  do

    # YYText
    pod  'YYText'
    
    # SDWebImage
    pod  'SDWebImage'

    # 曲线动画
#    pod 'GaiaMotionCurve', :path => '../../GaiaMotionCurve/src/iOS'
    pod 'GaiaMotionCurve', '0.1.0'

end

