// 在此处导出方法，依赖方才可以使用
export { GXComponent } from "./src/main/ets/component/GXComponent"

export { GXMeasureSize } from './src/main/ets/gaiax/GXMeasureSize'

export { GXTemplate } from './src/main/ets/gaiax/GXTemplate'

export { GXTemplateItem } from './src/main/ets/gaiax/GXTemplateItem'

export { GXTemplateData } from './src/main/ets/gaiax/GXTemplateData'

export { GXIExtensionTemplateSource } from './src/main/ets/gaiax/GXIExtensionTemplateSource'

export { gxRegisterCenter } from './src/main/ets/gaiax/GXRegisterCenter'
