import GXAbility from './GXAbility';

export class GXAbility1 extends GXAbility {
}

export class GXAbility2 extends GXAbility {
}

export class GXAbility3 extends GXAbility {
}

export class GXAbility4 extends GXAbility {
}

export class GXAbility5 extends GXAbility {
}

export class GXAbility6 extends GXAbility {
}

export class GXAbility7 extends GXAbility {
}

export class GXAbility8 extends GXAbility {
}

export class GXAbility9 extends GXAbility {
}

export class GXAbility10 extends GXAbility {
}

export class GXAbility11 extends GXAbility {
}

export class GXAbility12 extends GXAbility {
}

export class GXAbility13 extends GXAbility {
}

export class GXAbility14 extends GXAbility {
}

export class GXAbility15 extends GXAbility {
}

export class GXAbility16 extends GXAbility {
}

export class GXAbility17 extends GXAbility {
}

export class GXAbility18 extends GXAbility {
}

export class GXAbility19 extends GXAbility {
}

export class GXAbility20 extends GXAbility {
}