profile = "compiler"
changelog-seen = 2

[build]
sanitizers = true
profiler = true

[target.aarch64-unknown-linux-ohos]
cc = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/aarch64-unknown-linux-ohos-clang.sh"
cxx = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/aarch64-unknown-linux-ohos-clang++.sh"
ar = "/Users/biezhihua/Software/Huawei/sdk/openharmony/9/native/llvm/bin/llvm-ar"
ranlib = "/Users/biezhihua/Software/Huawei/sdk/openharmony/9/native/llvm/bin/llvm-ranlib"
linker  = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/aarch64-unknown-linux-ohos-clang.sh"

[target.armv7-unknown-linux-ohos]
cc = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/armv7-unknown-linux-ohos-clang.sh"
cxx = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/armv7-unknown-linux-ohos-clang++.sh"
ar = "/Users/biezhihua/Software/Huawei/sdk/openharmony/9/native/llvm/bin/llvm-ar"
ranlib = "/Users/biezhihua/Software/Huawei/sdk/openharmony/9/native/llvm/bin/llvm-ranlib"
linker  = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/armv7-unknown-linux-ohos-clang.sh"

[target.x86_64-unknown-linux-ohos]
cc = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/x86_64-unknown-linux-ohos-clang.sh"
cxx = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/x86_64-unknown-linux-ohos-clang++.sh"
ar = "/Users/biezhihua/Software/Huawei/sdk/openharmony/9/native/llvm/bin/llvm-ar"
ranlib = "/Users/biezhihua/Software/Huawei/sdk/openharmony/9/native/llvm/bin/llvm-ranlib"
linker  = "/Users/biezhihua/WorkSpace/YKGAIAX/GaiaX/harmony/x86_64-unknown-linux-ohos-clang.sh"
