// https://www.jiyik.com/tm/xwzj/prolan_1622.html
// File '/Users/biezhihua/WorkSpace/YKHarmony/GaiaXHarmony/GaiaXDemo/oh_modules/.ohpm/gxstretch@cu+tbkcd+sru8fpeb3hodoi4i1k=/oh_modules/gxstretch/Index.ets' is not a module. <ArkTSCheck>

export { Layout } from './src/main/ets/stretch/Layout';

export { Stretch } from './src/main/ets/stretch/Stretch';

export { Node } from './src/main/ets/stretch/Node';

export { Style,
  AlignItems,
  AlignSelf,
  AlignContent,
  Direction,
  Display,
  FlexDirection,
  JustifyContent,
  Overflow,
  PositionType,
  FlexWrap,
  Size,
  Rect,
  Dim,
  DimPoints,
  DimPercent,
  DimAuto,
  DimUndefined,
  Undefined,
  Auto } from './src/main/ets/stretch/Style';