name: Analyze CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        working-directory: ./GaiaXAnalyze/GXAnalyzeAndroid
        ndk: 21.0.6113669
        cmake: 3.10.2.4988404
        script: ./gradlew connectedCheck && ./gradlew connectedAndroidTest
