name: Analyze CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build before
      run: ls -ll
    - name: run emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 28
          script: ./gradlew connectedCheck
    - name: run analyze test
      run: cd ./GaiaXAnalyze/GXAnalyzeAndroid && ./gradlew connectedAndroidTest
